---
- hosts: web
  tasks:
  - name: Install Apache
    yum: name=httpd state=present
  - name: Start Apache
    service: name=httpd state=started

  - name: Install Java JDK
    yum: name=java-1.8.0-openjdk.x86_64 state=present
  - name: Install Java JDK_devel
    yum: name=java-1.8.0-openjdk-devel.x86_64 state=present
  - name: Install Java
    yum: name=java state=present